server:
  port: 8087

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  routes:
    provider: /provider/**
    consumer: /consumer/**
  prefix: /api