server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tnew1?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
  application:
    name: provider

mybatis:
  type-aliases-package: com.pojo


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka